Sentiment-Flask-App/app.py
from flask import Flask, render_template, request, url_for, jsonify
from flask_bootstrap import Bootstrap
from flask_restful import Api, Resource
from werkzeug.utils import redirect

import pandas as pd
import numpy as np

# NLP
from textblob import TextBlob
import textprocess.kelime_bol as bol
import textprocess.kelimelerine_ayir as ayir
import time
import datetime
import uuid

from common.database import Database
from common.logistic_model import LogisticModel
from common.rnn_model import RnnModel
from common.utils import Utils

from models.predicts.predict import Predict
from models.predicts.views import predict_blueprint


app = Flask(__name__)
Bootstrap(app)
api = Api(app)


# zemberek sentence normalization
import jpype
zemberekApi = None


with app.app_context():
    zemberekpath = "./zemberek_python/zemberek-full.jar"
    jpype.startJVM(jpype.get_default_jvm_path(), "-Djava.class.path=" + zemberekpath, "-ea")
    #jpype.attachThreadToJVM()
    Zemberek = jpype.JClass("org.ingbank.zemberek.Zemberek")
    # zemberekApi = Zemberek()
    zemberekApi = Zemberek()

    # initialize database and models
    Utils.initialize()
    Database.initialize()
    LogisticModel.initialize()
    RnnModel.initialize()


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/predicted', methods=['GET'])
def predicted():
    cursor = Predict.find({}, {'Text': 1, 'Normalized_Text': 1, 'Score': 1, 'Date': 1, '_id': 0}).sort('Date', -1)
    df_table = pd.DataFrame(list(cursor))

    return render_template('predicted.html', df_table=df_table)


@app.route('/analyse', methods=['POST'])
def analyse():
    start = time.time()
    if request.method == 'POST':
        originaltext = request.form['rawtext']
        # if original text is empty do nothing
        if str(originaltext).strip() == '':
            return redirect(url_for('index'))

        # preprocess text
        rawtext = str(originaltext).strip().replace(u"I", u"ı").replace(u"İ", u"i")
        rawtext = rawtext.lower()

        # zemberek sentence normalization
        jpype.attachThreadToJVM()
        rawtext = zemberekApi.sentenceNormalizer(rawtext)

        # remove stop words - stop word de gereksiz kelimeler çıkıcak !!!
        rawtext = Utils.remove_stopwords(rawtext)

        # refresh blob object
        blob = TextBlob(rawtext)

        # positive and negative meaning of the word - meaninde de negatif pozitif kelimeleri ekle
        wordList = list(blob.words)
        meaning = ayir.anlam(wordList)

        # NLP Stuff goes here
        sentiment_prediction = LogisticModel.logistic_predict(rawtext)
        polarity_prediction = RnnModel.rnn_predict(rawtext)

        sentimentScore = Utils.calculate_sentiment_score(meaning, sentiment_prediction[0], polarity_prediction[0][0])

        end = time.time()
        final_time = end - start

        try:
            # save predicted result to mongodb
            predictObj = Predict(text=originaltext, normalized_text=rawtext, score=int(sentimentScore),
                             changed_score=None, sentiment=int(sentiment_prediction[0]),
                             polarity=str(polarity_prediction[0][0]), polarity_score=int(polarity_prediction[0][0] * 100),
                             meaning=int(meaning), time=str(final_time), date=datetime.datetime.utcnow(),
                             _id=uuid.uuid4().hex)
            predictObj.save_to_mongo()
        except:
            pass

    return render_template('index.html', received_text=rawtext,
                           meaning=meaning,sentiment=sentiment_prediction[0],
                           polarity=polarity_prediction[0][0], score=sentimentScore,
                           summary='', final_time=final_time)


def generateReturnDictionary(status, msg):
    retJson = {
        "status": status,
        "msg": msg
    }
    return retJson


class GetSentiment(Resource):
    def post(self):
        start = time.time()

        postedData = request.get_json()
        originaltext = postedData["text"]
        # if original text is empty do nothing
        if str(originaltext).strip() == '':
            return generateReturnDictionary(301, "Invalid Text")

        # preprocess text
        rawtext = str(originaltext).strip().replace(u"I", u"ı").replace(u"İ", u"i")
        rawtext = rawtext.lower()

        # zemberek sentence normalization
        jpype.attachThreadToJVM()
        rawtext = zemberekApi.sentenceNormalizer(rawtext)

        # remove stop words
        rawtext = Utils.remove_stopwords(rawtext)

        # refresh blob object
        blob = TextBlob(rawtext)

        # positive and negative meaning of the word
        wordList = list(blob.words)
        meaning = ayir.anlam(wordList)

        # NLP Stuff goes here
        sentiment_prediction = LogisticModel.logistic_predict(rawtext)
        polarity_prediction = RnnModel.rnn_predict(rawtext)

        sentimentScore = Utils.calculate_sentiment_score(meaning, sentiment_prediction[0], polarity_prediction[0][0])

        end = time.time()
        final_time = end - start

        try:
            # save predicted result to mongodb
            predictObj = Predict(text=originaltext, normalized_text=rawtext, score=int(sentimentScore),
                             changed_score=None, sentiment=int(sentiment_prediction[0]),
                             polarity=str(polarity_prediction[0][0]), polarity_score=int(polarity_prediction[0][0] * 100),
                             meaning=int(meaning), time=str(final_time), date=datetime.datetime.utcnow(),
                             _id=uuid.uuid4().hex)
            predictObj.save_to_mongo()
        except:
            pass

        return jsonify(predictObj.api_json())


# Add Api Resources and Blueprints
api.add_resource(GetSentiment, '/sentiment')
app.register_blueprint(predict_blueprint, url_prefix="/predicts")

Sentiment-Flask-App/models/predicts/views.py
from flask import Blueprint, render_template, request, json, url_for, jsonify
from werkzeug.utils import redirect

from models.predicts.predict import Predict

predict_blueprint = Blueprint('predicts', __name__)


@predict_blueprint.route('/')
def index():
    predicts = Predict.all()
    return render_template('predicts/predict_list.html', predicts=predicts)


@predict_blueprint.route('/detail/<string:id>', methods=['GET', 'POST'])
def detail_page(id):
    predict = Predict.get_by_id(id)
    return render_template('predicts/predict_detail.html', predict=predict)


@predict_blueprint.route('/edit/<string:id>/<string:score>', methods=['GET', 'POST'])
def edit_page(id, score):
    try:
        if str(score) != 'None':
            final_score = int(score)
        else:
            final_score = None

        predict = Predict.get_by_id(id)
        predict.changed_score = final_score
        predict.save_to_mongo()

    except ValueError:
        pass

    return redirect(url_for('.detail_page', id=id))

Sentiment-Flask-App/templates/index.html
{% extends 'bootstrap/base.html' %}
{% block content %}

    <div class="container">
        <div class="jumbotron text-center">
            <h2>Natural Language Processing App</h2>
        </div>

    </div>

    <div class="container">
        <form action="{{url_for('analyse')}}" method="post" id="myform">

            <div class="form-group">
                <textarea name="rawtext" rows="3" class="form-control"></textarea>
            </div>
            <input type="submit" name="" value="Submit" class="btn btn-primary">
            <input type="reset" name="" value="Clear" class="btn btn-success">

            <a href="{{url_for('index')}}" type="button" class="btn btn-danger">Reset</a>

            <a href="{{url_for('predicts.index')}}" type="button" class="btn btn-link">Predicted Table</a>
        </form>
    </div>

    <br/>

    <div class="container">
        <div class="card">
            <div>
                <p>Analyzed Text:</p>
                <p><span style="color:blue;">{{ received_text }}</span></p>
            </div>


            <hr/>

            <div class="card-body">
                <p>Time Elapsed: <span style="color:red;">{{ final_time }} </span> seconds to analyse</p>
                <p>This text is about:</p>

                {% for i in summary %}
                <li>{{i}}
                    <a href="https://www.dictionary.com/browse/{{i}}?s=t" type="button"
                       target="_blank" class="btn btn-primary">
                        View
                    </a>
                </li>
                {% endfor %}
            </div>

            <table class="table table-striped table-dark">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">Sentiment Score</th>
                        <th scope="col">Meaning</th>
                        <th scope="col">Sentiment</th>
                        <th scope="col">Polarity</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Score:</th>
                        <th>{{ score }}</th>
                        <th>{{ meaning }}</th>
                        <th>{{ sentiment }}</th>
                        <th>{{ polarity }}</th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

Sentiment-Flask-App/templates/predicted.html
{% extends 'bootstrap/base.html' %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Details of Dataset</h2>
                <br/>
                <div id="myTableDiv">
                    {{ df_table.to_html(classes="table table-striped table-dark",na_rep="-") | safe}}
                </div>
                <br/>
                <a href="{{url_for('index')}}" type="button" class="btn btn-primary">Go Back</a>
            </div>
        </div>
    </div>

{% endblock %}

Sentiment-Flask-App/templates/predicts/predict_detail.html
{% extends 'bootstrap/base.html' %}
{% block content %}

<div class="container">
    <div class="jumbotron text-center">
        <h2>Sentiment Predict Detail</h2>
    </div>
</div>

<div class="center" style="margin-left:10px; margin-right:10px">
    <br/><br/>
    {% if predict %}
    <table id="predict-table" class="table table-striped table-dark" width="%100" cellspacing="0">
        <thead>
            <tr>
                <th>Text</th>
                <th>Normalized Text</th>
                <th>Sentiment Score</th>
                <th>Changed Score</th>
                <th>Elapsed Time</th>
                <th>Date</th>
                <th>Change To</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ predict.text }}</td>
                <td>{{ predict.normalized_text }}</td>
                <td>
                    {% if predict.score == 1 %}
                        <a href="#" class="btn btn-success" title="positive">Positive</a>
                    {% elif predict.score == 0 %}
                        <a href="#" class="btn btn-default" title="neutral">Neutral</a>
                    {% elif predict.score == -1 %}
                        <a href="#" class="btn btn-danger" title="negative">Negative</a>
                    {% endif %}
                </td>
                <td>
                    {% if predict.changed_score == 1 %}
                        <a href="#" class="btn btn-success" title="positive">Positive</a>
                    {% elif predict.changed_score == 0 %}
                        <a href="#" class="btn btn-default" title="neutral">Neutral</a>
                    {% elif predict.changed_score == -1 %}
                        <a href="#" class="btn btn-danger" title="negative">Negative</a>
                    {% else %}
                        {{ predict.changed_score }}
                    {% endif %}
                </td>
                <td>{{'%0.2f' % predict.time|float}}</td>
                <td>{{ predict.date.strftime('%d-%m-%Y %H:%M%:%S') }}</td>
                <td>
                    {% if predict.score != 1 %}
                        <a href="{{ url_for('predicts.edit_page', id=predict._id, score=1) }}"
                           class="btn btn-success" title="positive">Positive</a>
                    {% endif %}
                    {% if predict.score != 0 %}
                        <a href="{{ url_for('predicts.edit_page', id=predict._id, score=0) }}"
                           class="btn btn-default" title="neutral">Neutral</a>
                    {% endif %}
                    {% if predict.score != -1 %}
                        <a href="{{ url_for('predicts.edit_page', id=predict._id, score=-1) }}"
                           class="btn btn-danger" title="negative">Negative</a>
                    {% endif %}
                    {% if predict.changed_score != None %}
                        <a href="{{ url_for('predicts.edit_page', id=predict._id, score='None') }}"
                           class="btn btn-primary" title="none">None</a>
                    {% endif %}
                </td>
            </tr>
        </tbody>
    </table>
    {% else %}
    <div style="text-align: center">
        <h3> Eklenmiş kişi bulunmamaktadır. </h3>
    </div>
    {% endif %}
    <br/><br/>
    <a href="{{url_for('predicts.index')}}" type="button" class="btn btn-primary">Go Back</a>
</div>

{% endblock %}

Sentiment-Flask-App/templates/predicts/predict_list.html
{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

  <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">

  <script src="{{ url_for('static', filename='js/predicts.js') }}"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/predicts.css') }}">
  <!-- DataTables CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}">
  <!-- DataTables JS -->
  <script src="{{ url_for('static', filename='js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/dataTables.bootstrap.min.js') }}"></script>

  <!-- DataTables Responsive -->
  <script src="{{ url_for('static', filename='js/dataTables.responsive.min.js') }}"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.dataTables.min.css') }}">
  <!-- DataTables Row Reorder -->
  <script src="{{ url_for('static', filename='js/dataTables.rowReorder.min.js') }}"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/rowReorder.dataTables.min.css') }}">

  <!-- Datatables export CSS libraries -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/buttons.dataTables.min.css') }}">
  <!-- Datatables export JS libraries -->
  <script src="{{ url_for('static', filename='js/dataTables.buttons.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jszip.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/buttons.html5.min.js') }}"></script>

{% endblock %}

{% block content %}

<div class="container">
    <div class="jumbotron text-center">
        <h2>Sentiment Predicted Results</h2>
    </div>
</div>

<div class="center" style="margin-left:10px; margin-right:10px">
    {% if predicts %}
    <table id="predict-table" class="table table-striped table-dark" width="%100" cellspacing="0">
        <thead>
            <tr>
                <th>Text</th>
                <th>Normalized Text</th>
                <th>Sentiment Score</th>
                <th>Changed Score</th>
                <th>Elapsed Time</th>
                <th>Date</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
        {% for predict in predicts %}
            <tr>
                <td>{{ predict.text }}</td>
                <td>{{ predict.normalized_text }}</td>
                <td>
                    {% if predict.score == 1 %}
                        <a href="#" class="btn btn-success" title="positive">Positive</a>
                    {% elif predict.score == 0 %}
                        <a href="#" class="btn btn-default" title="neutral">Neutral</a>
                    {% elif predict.score == -1 %}
                        <a href="#" class="btn btn-danger" title="negative">Negative</a>
                    {% endif %}
                </td>
                <td>
                    {% if predict.changed_score == 1 %}
                        <a href="#" class="btn btn-success" title="positive">Positive</a>
                    {% elif predict.changed_score == 0 %}
                        <a href="#" class="btn btn-default" title="neutral">Neutral</a>
                    {% elif predict.changed_score == -1 %}
                        <a href="#" class="btn btn-danger" title="negative">Negative</a>
                    {% else %}
                        {{ predict.changed_score }}
                    {% endif %}
                </td>
                <td>{{'%0.2f' % predict.time|float}}</td>
                <td>{{ predict.date.strftime('%d-%m-%Y %H:%M%:%S') }}</td>
                <td>
                    <a href="{{ url_for('predicts.detail_page', id=predict._id) }}"
                       class="btn btn-primary" title="Details">Show Detail</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div style="text-align: center">
        <h3> Eklenmiş sentiment analizi bulunmamaktadır. </h3>
    </div>
    {% endif %}
    <a href="{{url_for('index')}}" type="button" class="btn btn-primary">Go Back</a>
</div>

{% endblock %}